package UI.CommandLineParsers.AsciiTableParser

import Services.ImageConvertors.AsciiConvertor.AsciiConvertor
import UI.CommandLineParsers.CommandLineParser

trait AsciiTableCommandLineParser extends CommandLineParser[AsciiConvertor]
