package UI.CommandLineParsers.AsciiTableParser.SpecializedAsciiParsers

import Core.Models.AsciiTable.AsciiTable
import Services.ImageConvertors.AsciiConvertor.AsciiConvertor
import UI.CommandLineParsers.SpecializedCommandLineParser
trait SpecializedAsciiTableCommandLineParser extends SpecializedCommandLineParser[AsciiConvertor]