package Services.CommandLineParsers.AsciiTableParser

import Services.CommandLineParsers.CommandLineParser
import Services.ImageConvertors.AsciiConvertor.AsciiConvertor
trait AsciiTableCommandLineParser extends CommandLineParser[AsciiConvertor]
