name: Scala CI

on:
  push:
    branches: [ github-actions ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    container:
      image: sbtscala/scala-sbt:eclipse-temurin-jammy-17.0.10_7_1.10.1_3.5.0

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Show sbt version
        run: sbt sbtVersion

      - name: Run tests with coverage
        run: sbt clean coverage test coverageReport

      - name: Upload coverage reports
        uses: actions/upload-artifact@v4
        with:
          name: scoverage-report
          path: target/scala-*/scoverage-*
